---
abstract: 'A tiny Perl code tokenizer.'
author:
  - 'Daniel Șuteu <trizen@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 0
generated_by: 'Module::Build version 0.4234, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-Tokenizer
provides:
  Perl::Tokenizer:
    file: lib/Perl/Tokenizer.pm
    version: '0.10'
recommends:
  Getopt::Std: '0'
  HTML::Entities: '0'
  Term::ANSIColor: '0'
  open: '0'
requires:
  Exporter: '0'
  perl: v5.18.0
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/trizen/Perl-Tokenizer/issues
  homepage: https://github.com/trizen/Perl-Tokenizer
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: https://github.com/trizen/Perl-Tokenizer
version: '0.10'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
